name: CLi_Tools
on: workflow_dispatch

jobs:
  flow:
    runs-on: macos-latest
    steps: 
      - name: Cache Tuist
        id: cache-tuist
        uses: actions/cache@v3
        with:
          path: |
            ~/.tuist
            ~/.tuist-bin
          key: tuist-cache-{{ runner.os }}-{{ hashFiles('**/tuist.yaml') }}
          restore-keys: |
            tuist-cache-{{ runner.os }}-
          
      - name: Install Tuist
        if: steps.cache-tuist.outputs.cache-hit != 'true'
        run: |
          bash <(curl -Ls https://install.tuist.io)
        
        
    
