name: CLi_Tools
on: workflow_dispatch

jobs:
  flow:
    runs-on: macos-latest
    steps: 
      - uses: actions/checkout@v3
      
      - name: Cache
        id: cache-tuist
        uses: action/cache@v4
        with:
          path: ~/.tuist
          key: ${{ runner.os }}-tuist
          
      - name: Install Tuist
        if: steps.cache-tuist.outputs.cache-hit != 'true'
        run: |
          bash <(curl -Ls https://install.tuist.io)
          which tuist
        
        
    
