name: CLi_Tools
on: workflow_dispatch

jobs:
  flow:
    runs-on: macos-latest
    steps: 
      - name: Install Tuist
        if: steps.cache-tuist.outputs.cache-hit != 'true'
        run: |
          bash <(curl -Ls https://install.tuist.io)
        
        
    
