name: lintAndTest

on: workflow_dispatch

jobs:

  success-build:

    runs-on: macos-latest

    steps:
      - name: load-project-files
        uses: actions/checkout@v4
      - name: test-project-files
        run: | 
          xcodebuild -project JuniosCI.xcodeproj \
                     -scheme TestSuccessScheme \
                     clean build test \
                     CODE_SIGN_STYLE=Manual \
                     CODE_SIGN_IDENTITY="" \
                     PROVISIONING_PROFILE_SPECIFIER="" \
                     CODE_SIGNING_ALLOWED=NO
          
          
