name: lintAndTest

on: workflow_dispatch

jobs:

  success-build:

    runs-on: macos-latest

    steps:
      - name: load-project-files
        uses: actions/checkout@v4
      
      - name: test-project-files
        run: | 
          ls -al
          cd JuniosCI
          xcodebuild clean test -project JuniosCI.xcodeproj -scheme TestSuccessScheme -destination 'platform=iOS simulator,name=iPhone 15 Pro,OS=17.0' CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO

  failure-build:

    runs-on: macos-latest

    steps:
      - name: load-project-files
        uses: actions/checkout@v4
      
      - name: test-project-files
        run: | 
          cd JuniosCI
          xcodebuild test -project JuniosCI.xcodeproj -scheme TestFailureScheme -destination 'platform=iOS simulator,name=iPhone 15 Pro,OS=17.0'
