name: Build Tuist project
on: workflow_dispatch

jobs:
  TestProject:
    runs-on: macos-latest
    env:
      tuist-version: "4.18.0"
    steps: 
      - name: Cache
        id: cache-tuist
        uses: actions/cache@v4
        with:
          path: |
            /usr/local/bin/tuist
          key: ${{ runner.os }}-tuist-"$tuist-version"
          
      - name: Install Tuist
        if: steps.cache-tuist.outputs.cache-hit != 'true'
        run: |
          bash <(curl -Ls https://install.tuist.io) --version "$tuist-version"
          which tuist

      - name: checkout repository
        uses: actions/checkout@v4
        

      - name: Test tuist
        run: |
          cd JuniosCITuist
          tuist generate
          tuist test
        
        
